version: '3.1'

services:

  mariadb:
    image: mysql:8.0
    restart: always
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      - MYSQL_PASSWORD=examplepass
      - MARIADB_USER=exampleuser
      - MYSQL_DATABASE=exampledb
      
  wordpress:
    image:  wordpress:latest                    # https://hub.docker.com/_/wordpress/
    restart: always
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb
    environment:
      - MYSQL_PASSWORD=examplepass
      - WORDPRESS_DATABASE_HOST=mariadb
      - WORDPRESS_DATABASE_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=exampleuser
      - WORDPRESS_DATABASE_NAME=exampledb
      
volumes:
  wordpress:
  mariadb:
